name: CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]
  schedule:
    # Run daily sanity check at 23:08 clock UTC
    - cron: "8 23 * * *"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  contrib-ut:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.16.x, 1.17.x]
    env:
      DOCKER: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: cache go mod
        uses: actions/cache@v2
        with:
          path: /go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/contrib/nydusify/go.sum', '**/contrib/ctr-remote/go.sum', '**/contrib/docker-nydus-graphdriver/go.sum', '**/contrib/nydus-overlayfs/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go
      - name: test contrib UT
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.43.0
          make all-contrib-test

  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache Nydus
        uses: Swatinem/rust-cache@v1
        with:
          target-dir: |
            ./target-fusedev
            ./target-virtiofs
          cache-on-failure: true
          key: ${{ runner.os }}-cargo-amd64
      - name: Cache Docker Layers
        uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true
      - name: Smoke Test
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.43.0
          echo Cargo Home: $CARGO_HOME
          echo Running User: $(whoami)
          make docker-smoke
          sudo chown -R $(id -un):$(id -gn) . ~/.cargo/

  macos-ut:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: build and check
        run: |
          rustup component add rustfmt && rustup component add clippy
          make macos-ut

  deny:
    name: Cargo Deny
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: EmbarkStudios/cargo-deny-action@v1
